### ISSUE TITLE
`rebuild solution` button from VS removes all source files

### ISSUE THREAD

**Issue by sungam3r** [SimonCropp/NullabilityInfo#18]
Hi, I decided to post issue here because for a long time I have a problem with building GraphQL.NET repo. This happened immediately after using Nullability.Source in this project:
![изображение](https://user-images.githubusercontent.com/21261007/204109581-9be0b141-5698-48a1-9941-4ecb822e6371.png)
![изображение](https://user-images.githubusercontent.com/21261007/204109862-f0d0d731-b1e0-4455-b50b-a64a30cb1539.png)

This error frustrated me with MSVS 2019. The same for MSVS 2022. Interesting that `dotnet build` from command line works without any error. Then if I rebuild solution from MSVS the error comes again. I found that after rebuild all the files from `graphql-dotnet\src\GraphQL\obj\Debug\netstandard2.0\NuGet\18DDE7FA843FFDD01ACD50BABCFD8EA1FF8B9B8B\Nullability.Source\2.0.4\Nullability.Source` folder disappear. `dotnet build` "heals" this situation - all files appear again. 

GraphQL.NET consumes this package in such a way:
```xml
 <PackageReference Include="Nullability.Source" Version="2.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

This error is very annoying, because it often hides other real errors, while in itself it does not prevent successful compilation - I can just run tests and all needed files appear again. The long story short - fore some reason `rebuild solution` button from VS removes all source files from `graphql-dotnet\src\GraphQL\obj\Debug\netstandard2.0\NuGet\18DDE7FA843FFDD01ACD50BABCFD8EA1FF8B9B8B\Nullability.Source\2.0.4\Nullability.Source`.

**Comment by sungam3r** [comment]
ping @Shane32 . Once I already talked you about this issue.

**Comment by Shane32** [comment]
It happens on my PC as well. I’m unaware of a solution. This is the only project that I use that has a nuget package with source files.

**Comment by SimonCropp** [comment]
so what am i doing wrong in my source package?

**Comment by sungam3r** [comment]
I don't know. Maybe it is some VS issue that correlates with internals of that package.

**Comment by sungam3r** [comment]
Maybe it is somehow related to [nuget transformations](https://learn.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations). I see you distribute pp files instead of cs but I don't see any transformation marker inside these files. Maybe try to switch to "normal" static cs files?

**Comment by SimonCropp** [comment]
can u try 2.1.0

**Comment by SimonCropp** [comment]
note i use Rider and do not have this problem

**Comment by sungam3r** [comment]
The error is gone and files become visible in solution
![изображение](https://user-images.githubusercontent.com/21261007/205519998-1775b50d-b52f-4a5b-a092-a08f63d429d5.png)

@Shane32 try too
