### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by MaceWindu** [SimonCropp/NullabilityInfo#52]
Current version of `Nullability.Source` (2.1.0) triggers error from CA1822 analyzer when enabled:

```cs
.nuget\packages\nullability.source\2.1.0\contentFiles\cs\netstandard2.0\Nullability.Source\NullabilityInfoContext.cs(578,22): Error CA1822: Member 'TryPopulateNullabilityInfo' does not access instance data and can be marked as static
```

I see it was already fixed in source here https://github.com/SimonCropp/NullabilityInfo/commit/d91fc09e6a18f4ce48a10b232d5c878a70a8aaba, so no changes to code required

**Comment by SimonCropp** [comment]
done
