### ISSUE TITLE
Patch source within v1.0.5 to run on .NET Standard 2.0

### ISSUE THREAD

**Issue by Shane32** [SimonCropp/NullabilityInfo#9]
The new source isn't compatible with .NET Standard 2.0 frameworks.

Line 210: Can't use `[^1]` for array indexer
Line 492: `IsGenericMethodParameter` isn't recognized
Line 518: `IsGenericMethodParameter` isn't recognized

**Comment by Shane32** [comment]
@SimonCropp Probably want to deprecate v1.0.5 within NuGet also...

**Comment by SimonCropp** [comment]
released to nuget. and i also added a fake project that consumes the source under netstandard2.0 so we wont accidentally deploy this kind of broken source again.

**Comment by Shane32** [comment]
Thanks appreciate it!!!
